# This notebook contains information with examples for the most commonly used (for beginners as well as advanced users) functions and techniques in Numpy.
## The notebook was used by me (Niv Rave) to be shared and to assist student, beginners and those who just need the simple 'copy and paste' to improve their performance.

## This notebook contains:
1. Basic array creation
2. Basic dimensions/shapes
3. Broadcasting
4. Array indexing / slicing / masking
5. Searching and indices
6. Array creation functions (Advanced)
7. Random numbers and sampling
8. Advanced array manipulation
9. Statistics
10. Linear algebra


## Each area contains examples, explanations and printing of the data and the output, and at the end of every area (well, almost all of them) there is a cell containing additional links and information.

In [1]:
#import numpy -> use numpy. to use the library
import numpy as np# use np. to use the library

# 1. Basic array creation

In [2]:
a = np.array([1,2,3])
b = np.array([1.,2.,3.])
c = np.array([True, True, False])

In [3]:
print('a:')
print(a)
print(type(a))
print(a.dtype)

a:
[1 2 3]
<class 'numpy.ndarray'>
int32


In [4]:
print('b:')
print(b)
print(type(b))
print(b.dtype)

b:
[1. 2. 3.]
<class 'numpy.ndarray'>
float64


In [5]:
print('c:')
print(c)
print(type(c))
print(c.dtype)

c:
[ True  True False]
<class 'numpy.ndarray'>
bool


In [6]:
# Create array using existing arrays
d = np.array([a, a, a])
print('d:')
print(d)
print(type(d))
print(d.dtype)

d:
[[1 2 3]
 [1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>
int32


# 2. Basic dimensions/shapes

In [7]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[1,2,3]])
c = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [8]:
# 1D array
print('a:')
print(a)
print('ndim - number of dimensions:')
print(a.ndim)
print('shape:')
print(a.shape)
print('Number of elements = ' + str(a.shape[0]))

a:
[1 2 3]
ndim - number of dimensions:
1
shape:
(3,)
Number of elements = 3


In [9]:
# 2D array
print('b:')
print(b)
print('ndim - number of dimensions:')
print(b.ndim)
print('shape:')
print(b.shape)
print('Number of 1D arrays = '+str(b.shape[0])+', Number of elements in each 1D array = '+str(b.shape[1]))

b:
[[1 2 3]
 [1 2 3]]
ndim - number of dimensions:
2
shape:
(2, 3)
Number of 1D arrays = 2, Number of elements in each 1D array = 3


In [10]:
# 3D array
print('c:')
print(c)
print('ndim - number of dimensions:')
print(c.ndim)
print('shape:')
print(c.shape)
print('Number of 2D arrays = '+str(c.shape[0])+', Number of 1D arrays = '+str(c.shape[1])+', Number of elements in each 1D array = '+str(c.shape[2]))
print(c.shape[0],c.shape[1],c.shape[2])

c:
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
ndim - number of dimensions:
3
shape:
(2, 2, 3)
Number of 2D arrays = 2, Number of 1D arrays = 2, Number of elements in each 1D array = 3
2 2 3


In [11]:
print('Access 1st element in each array:')
print('a:')
print(a[0])
print('b:')
print(b[0,0])
print('c:')
print(c[0,0,0])

Access 1st element in each array:
a:
1
b:
1
c:
1


In [12]:
i = 2
print('Access i\'th element in each array:')
print('a:')
print(a[i])
print('b:')
print(b[0,2])
print('c:')
print(c[0,0,i])

Access i'th element in each array:
a:
3
b:
3
c:
3


### numpy.reshape()
#### Reshape a numpy array without changing the data.
numpy.reshape(a, newshape, order='C')

In [13]:
a = np.array([1,2,3,4,5,6])
print('a:')
print(a)
reshaped = a.reshape((2, 3))
print('reshaped 2x3:')
print(reshaped)
reshaped = a.reshape((3, 2))
print('reshaped 3x2:')
print(reshaped)
print('a:')
print(a)

a:
[1 2 3 4 5 6]
reshaped 2x3:
[[1 2 3]
 [4 5 6]]
reshaped 3x2:
[[1 2]
 [3 4]
 [5 6]]
a:
[1 2 3 4 5 6]


### numpy.transpose(), .T
#### Returns the array transpose (reverse axes)
numpy.transpose(a, axes=None)

In [14]:
a = np.array([1,2,3,4,5,6]).reshape((2,3))
a_transpose = np.transpose(a)
a_T = a.T
print('a:')
print(a)
print('a transpose using np.transpose():')
print(a_transpose)
print('a transpose using a.T:')
print(a_T)

a:
[[1 2 3]
 [4 5 6]]
a transpose using np.transpose():
[[1 4]
 [2 5]
 [3 6]]
a transpose using a.T:
[[1 4]
 [2 5]
 [3 6]]


In [15]:
#a = np.array([[1,2],[3,4]])
a = np.array([[1,2,3],[4,5,6]])
print('a:')
print(a)
a_transpose = np.transpose(a)
a_transpose_1 = np.transpose(a,(0,1))
a_transpose_2 = np.transpose(a,(1,0))
print('a transpose using np.transpose():')
print(a_transpose)
print('a transpose using np.transpose() axis = (0,1):') # keep the same axis
print(a_transpose_1)
print('a transpose using np.transpose() axis = (1,0):') # change axis order - like a 2d matrix transpose
print(a_transpose_2)

a:
[[1 2 3]
 [4 5 6]]
a transpose using np.transpose():
[[1 4]
 [2 5]
 [3 6]]
a transpose using np.transpose() axis = (0,1):
[[1 2 3]
 [4 5 6]]
a transpose using np.transpose() axis = (1,0):
[[1 4]
 [2 5]
 [3 6]]


In [16]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('a:')
print(a)
# transpose in row/col axes (the 'inside' matrix)
a_transpose = np.transpose(a,(0,2,1))
print('a transpose using np.transpose() axis = (0,2,1):')
print(a_transpose)
a_transpose = np.transpose(a,(0,1,2))
print('a transpose using np.transpose() axis = (0,1,2):')
# transpose in other axes combinations
print(a_transpose)
a_transpose = np.transpose(a,(1,0,2))
print('a transpose using np.transpose() axis = (2,1,0):')
print(a_transpose)
a_transpose = np.transpose(a,(2,1,0))
print('a transpose using np.transpose() axis = (2,0,1):')
print(a_transpose)

a:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
a transpose using np.transpose() axis = (0,2,1):
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]
a transpose using np.transpose() axis = (0,1,2):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
a transpose using np.transpose() axis = (2,1,0):
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
a transpose using np.transpose() axis = (2,0,1):
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


# 3. Broadcasting
### Numpy enables different explicit and un explicit methods to broadcast arrays of different shapes and dimensions
### Find more at: https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html

In [17]:
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])
broadcasted = np.broadcast(a, b) # Returns a broadcast object
broadcasted_extracted = np.zeros(broadcasted.shape)
broadcasted_extracted.flat = [u+v for (u,v) in broadcasted] # using '+' for sum, change to get other results
print('a:')
print(a)
print('b:')
print(b)
print('broadcasted object:')
print(broadcasted)
print('broadcasted result after extracting:')
print(broadcasted_extracted)
# Output will be:
# 1+1 1+2 1+3
# 2+1 2+2 2+3
# 3+1 3+2 3+3
# Each 1x1 array in 'a' will turn into a 1x3 (turning 'a' from a 3x1 to a 3x3 array)
# and will be added to the 1x3 array 'b', resulting in the given 3x3 array above

a:
[[1]
 [2]
 [3]]
b:
[1 2 3]
broadcasted object:
broadcasted result after extracting:
[[2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


In [18]:
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])
broadcasted = a+b
print('a:')
print(a)
print('b:')
print(b)
print('broadcasted result:')
print(broadcasted)

a:
[[1]
 [2]
 [3]]
b:
[1 2 3]
broadcasted result:
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [19]:
a = np.array([1, 2, 3])
print('a:')
print(a)
print('a + 5:') # will broadcast 5 to [5, 5, 5]
print(a+5)

a:
[1 2 3]
a + 5:
[6 7 8]


# 4. Array indexing / slicing / masking

In [20]:
# Notice that index counting starts at '0' and elemnts start at '1' (zeroth index = first element)
a = np.array([1,2,3,4,5,6,7,8,9,10])
print('a:')
print(a)
print('First 3 elements:')
print(a[:3])
print('Elements 2-6:')
print(a[2:7])
print('Elements 7-8:')
print(a[7:9])
print('Last 3 elements:')
print(a[7:])

a:
[ 1  2  3  4  5  6  7  8  9 10]
First 3 elements:
[1 2 3]
Elements 2-6:
[3 4 5 6 7]
Elements 7-8:
[8 9]
Last 3 elements:
[ 8  9 10]


In [21]:
# Notice that index counting starts at '0' and elemnts start at '1' (zeroth index = first element)
a = np.array([1,2,3,4,5,6,7,8,9,10])
print('a:')
print(a)
print('Every other element:')
print(a[::2])
print('Every third element:')
print(a[::3])
print('Reverse array:')
print(a[::-1])
print('Reverse array every second element:')
print(a[::-2])

a:
[ 1  2  3  4  5  6  7  8  9 10]
Every other element:
[1 3 5 7 9]
Every third element:
[ 1  4  7 10]
Reverse array:
[10  9  8  7  6  5  4  3  2  1]
Reverse array every second element:
[10  8  6  4  2]


In [22]:
# Notice that index counting starts at '0' and elemnts start at '1' (zeroth index = first element)
a = np.array([1,2,3,4,5,6,7,8,9,10])
print('a:')
print(a)
print('1st, 2nd and 5th elements:')
print(a[[0,1,4]])
print('1st and last elements:')
print(a[[0,-1]])
print('1st , middle and last elements:')
print(a[[0,int(len(a)/2),-1]])

a:
[ 1  2  3  4  5  6  7  8  9 10]
1st, 2nd and 5th elements:
[1 2 5]
1st and last elements:
[ 1 10]
1st , middle and last elements:
[ 1  6 10]


In [23]:
# Reversing a single dimension can be very helpful (used in computer vision applications when integrating open-cv and matplotlib)
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('a:')
print(a)
print('a reversed on 3rd dimension:')
print(a[::-1])

a:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
a reversed on 3rd dimension:
[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


Boolean masking (will create a new array - similar to copy - read in the following sections)

In [24]:
# Notice that index counting starts at '0' and elemnts start at '1' (zeroth index = first element)
a = np.array([1,2,3,4,5,6,7,8])
masked_direct = a[[True, True, False, False, False, False, False, False]]
masked_greater3 = a[a>3]
masked_between25 = a[(a>2) & (a<5)] # & = and
masked_under3_over6 = a[(a<3) | (a>6)] # | = or
masked_even = a[a%2==0]
masked_odd = a[~(a%2==0)]
print('a:')
print(a)
print('masked, first 2 elements only:')
print(masked_direct)
print('masked, only a>3:')
print(masked_greater3)
print('masked, only 2<a<5:')
print(masked_between25)
print('masked, only 3>a or a>6:')
print(masked_under3_over6)
print('masked, only even values:')
print(masked_even)
print('masked, only odd values:')
print(masked_odd)

a:
[1 2 3 4 5 6 7 8]
masked, first 2 elements only:
[1 2]
masked, only a>3:
[4 5 6 7 8]
masked, only 2<a<5:
[3 4]
masked, only 3>a or a>6:
[1 2 7 8]
masked, only even values:
[2 4 6 8]
masked, only odd values:
[1 3 5 7]


#### Creating a new array using the elements of an existing one will not copy those elements and any manipulation on the original array will also affect the values in the "copied" one.
#### To get over that (if we want to) we will create a copy of the original array using the '.copy()' function

In [25]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print('After creating a:')
print('a:')
print(a)
b = a[::2]
c = a[::2].copy()
print('After creating b, c:')
print('a:')
print(a)
print('b:')
print(b)
print('c:')
print(c)
a[0] = 100
print('After changing a[0] value to '"'100'"':')
print('a:')
print(a)
print('b:')
print(b)
print('c:')
print(c)

After creating a:
a:
[ 1  2  3  4  5  6  7  8  9 10]
After creating b, c:
a:
[ 1  2  3  4  5  6  7  8  9 10]
b:
[1 3 5 7 9]
c:
[1 3 5 7 9]
After changing a[0] value to '100':
a:
[100   2   3   4   5   6   7   8   9  10]
b:
[100   3   5   7   9]
c:
[1 3 5 7 9]


# 5. Searching and indices

### Some of the commonly used array searching and filtering methods.
### Find more at: https://numpy.org/doc/stable/reference/routines.sort.html
Numpy provides methods that help analyzing the arrays in terms of 'filtering', getting indices and values that match a desired condition and more.

### numpy.argmin()
#### Returns an array containing the indices of the minimum values along an axis
numpy.argmin(a, axis=None, out=None, *, keepdims=False)

In [26]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = a.reshape((2, 5))
argmin_a = np.argmin(a)
argmin_b = np.argmin(b, axis=1)
print(f'argmin in array a is at index {argmin_a}')
print(f'argmin in array b is at index {argmin_b}')

argmin in array a is at index 0
argmin in array b is at index [0 0]


In [27]:
a = np.array([1,0,3,4,5,6,7,8,0,10])
b = a.reshape((2, 5))
argmin_b_axis0 = np.argmin(b)
argmin_b_axis1 = np.argmin(b, axis=1)
print(f'argmin in array b is at index {argmin_b_axis0}')# Treats b as a flattened array (1D)
print(f'argmin in array b is at index {argmin_b_axis1}')# Returns the argmin index in each array in axis 1

argmin in array b is at index 1
argmin in array b is at index [1 3]


### numpy.argmax()
#### Returns an array containing the indices of the maximum values along an axis
numpy.argmax(a, axis=None, out=None, *, keepdims=False)

In [28]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = a.reshape((2, 5))
argmax_a = np.argmax(a)
argmax_b = np.argmax(b, axis=1)
print(f'argmax in array a is at index {argmax_a}')
print(f'argmax in array b is at index {argmax_b}')

argmax in array a is at index 9
argmax in array b is at index [4 4]


In [29]:
a = np.array([1,0,35,4,5,12,7,8,0,4])
b = a.reshape((2, 5))
argmax_b_axis0 = np.argmax(b)
argmax_b_axis1 = np.argmax(b, axis=1)
print(f'argmax in array b is at index {argmax_b_axis0}')# Treats b as a flattened array (1D)
print(f'argmax in array b is at index {argmax_b_axis1}')# Returns the argmax index in each array in axis 1

argmax in array b is at index 2
argmax in array b is at index [2 0]


### numpy.nonzero()
#### Returns an array containing the indices of the elements that are non zero
numpy.nonzero(a)

In [30]:
a = np.array([1,0,35,0,5,12,7,8,0,4])
non_zeros = np.nonzero(a)
print('a:')
print(a)
print('non zeros:')
print(non_zeros)

a:
[ 1  0 35  0  5 12  7  8  0  4]
non zeros:
(array([0, 2, 4, 5, 6, 7, 9], dtype=int64),)


In [31]:
a = np.array([1,0,35,4,5,12,7,8,0,4])
b = a.reshape((2, 5))
non_zeros_a = np.nonzero(a)
non_zeros_b = np.nonzero(b)
print('a:')
print(a)
print('non zeros a:')
print(non_zeros_a)
print('b:')
print(b)
print('non zeros b:')
print(non_zeros_b)

a:
[ 1  0 35  4  5 12  7  8  0  4]
non zeros a:
(array([0, 2, 3, 4, 5, 6, 7, 9], dtype=int64),)
b:
[[ 1  0 35  4  5]
 [12  7  8  0  4]]
non zeros b:
(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 2, 3, 4, 0, 1, 2, 4], dtype=int64))


In [32]:
# Find the indices where the value is greater than 6 - where the condition is met
a = np.array([1,0,35,0,5,12,7,8,0,4])
non_zeros = np.nonzero(a>6)
print('a:')
print(a)
print('non zeros:')
print(non_zeros)

a:
[ 1  0 35  0  5 12  7  8  0  4]
non zeros:
(array([2, 5, 6, 7], dtype=int64),)


# 6. Array creation functions (Advanced)

### Some of the commonly used array creation methods.
### Find more at: https://numpy.org/doc/stable/reference/routines.array-creation.html
Numpy provides many array creation patterns that can assist, make the code more readable and demand less actions to create the desired type of array.

### numpy.zeros()
#### Create a numpy array containing zeros. Default data type = float
numpy.zeros(shape, dtype=float, order='C', *, like=None)

In [33]:
# Create a single size 5 array
zeros = np.zeros(5)
print(zeros)
print(zeros.dtype)

[0. 0. 0. 0. 0.]
float64


In [34]:
# Create a 2x2 array
zeros = np.zeros((2,2))
print(zeros)
print(zeros.dtype)

[[0. 0.]
 [0. 0.]]
float64


In [35]:
# Create a 2x2x2 array
zeros = np.zeros((2,2,2),dtype=np.float32)
print(zeros)
print(zeros.dtype)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
float32


In [36]:
zeros = np.zeros((2,2),dtype=int)
print(zeros)
print(zeros.dtype)

[[0 0]
 [0 0]]
int32


In [37]:
zeros = np.zeros((2,2),dtype='uint8') # Unsigned int, useful in computer vision applications and more
print(zeros)
print(zeros.dtype)

[[0 0]
 [0 0]]
uint8


### numpy.zeros_like()
#### Create a numpy array based on an existing array's shape and data type initialized with all 'zeros'
numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)

In [38]:
c = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print('c:')
print(c)
print(c.dtype)
print('zeros like c:')
zeros = np.zeros_like(c)
print(zeros)
print(zeros.dtype)

c:
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
int32
zeros like c:
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
int32


### numpy.ones()
#### Create a numpy array containing ones. Default data type = float
numpy.ones(shape, dtype=None, order='C', *, like=None)

In [39]:
# Create a single size 5 array
ones = np.ones(5)
print(ones)
print(ones.dtype)

[1. 1. 1. 1. 1.]
float64


In [40]:
# Create a 2x2 array
ones = np.ones((2,2))
print(ones)
print(ones.dtype)

[[1. 1.]
 [1. 1.]]
float64


In [41]:
# Create a 2x2x2 array
ones = np.ones((2,2,2),dtype=np.float32)
print(ones)
print(ones.dtype)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
float32


In [42]:
ones = np.ones((2,2),dtype=int)
print(ones)
print(ones.dtype)

[[1 1]
 [1 1]]
int32


In [43]:
ones = np.ones((2,2),dtype='uint8') # Unsigned int, useful in computer vision applications and more
print(ones)
print(ones.dtype)

[[1 1]
 [1 1]]
uint8


### numpy.ones_like()
#### Create a numpy array based on an existing array's shape and data type initialized with all 'ones'
numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)

In [44]:
c = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print('c:')
print(c)
print(c.dtype)
print('ones like c:')
ones = np.ones_like(c)
print(ones)
print(ones.dtype)

c:
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
int32
ones like c:
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int32


### numpy.arange()
#### Create a numpy array initialized with values in a given range and using a given step size (default=1)
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

In [45]:
a = np.arange(10)
print('a:')
print(a)
print(a.dtype)

a:
[0 1 2 3 4 5 6 7 8 9]
int32


In [46]:
a = np.arange(10.0,30.0)
print('a:')
print(a)
print(a.dtype)

a:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29.]
float64


In [47]:
a = np.arange(10,30,2)
print('a:')
print(a)
print(a.dtype)

a:
[10 12 14 16 18 20 22 24 26 28]
int32


### numpy.linspace()
#### Create a numpy array initialized with values evenly spaced over an interval
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [48]:
a = np.linspace(0, 10)
print('a:')
print(a)
print(a.dtype)
print(len(a))

a:
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
float64
50


In [49]:
a = np.linspace(0, 10, 10)
print('a:')
print(a)
print(a.dtype)
print(len(a))

a:
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
float64
10


In [50]:
a = np.linspace(0, 10, 10, endpoint=False)
print('a:')
print(a)
print(a.dtype)
print(len(a))

a:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
10


In [51]:
a = np.linspace(0, 10, 10, dtype='uint8', endpoint=False)
print('a:')
print(a)
print(a.dtype)
print(len(a))

a:
[0 1 2 3 4 5 6 7 8 9]
uint8
10


### numpy.logspace()
#### Create a numpy array initialized with values evenly spaced on a log scale, starting at base^start and end at base^stop
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)

In [52]:
a = np.logspace(2.0, 3.0, num=4)
print('a:')
print(a)
print(a.dtype)
print(len(a))

a:
[ 100.          215.443469    464.15888336 1000.        ]
float64
4


In [53]:
a = np.logspace(1, 10, num=10, base=2, dtype=np.float64)
print('a:')
print(a)
print(a.dtype)
print(len(a))

a:
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
float64
10


### Other array creation methods
#### Numpy provides many different array creation methods, such as:
#### Empty - https://numpy.org/doc/stable/reference/generated/numpy.empty.html
#### Eye (I matrix) - https://numpy.org/doc/stable/reference/generated/numpy.eye.html
#### Identity - https://numpy.org/doc/stable/reference/generated/numpy.identity.html

# 7. Random numbers and sampling

### Some of the commonly used methods for creating random numbers, random arrays and sampling.
### Find more at: https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random
Random numbers is used in many applications, such as data processing (splitting datasets), noise creation, testing etc.

### numpy.random.rand()
#### Generate random numbers in a given shape, uniformly distributed over [0, 1)
random.rand(d0, d1, ..., dn)

In [54]:
rand_array = np.random.rand(5)
print('rand_array:')
print(rand_array)
print(rand_array.dtype)
print(len(rand_array))

rand_array:
[0.64997785 0.83527914 0.1841282  0.53106848 0.71227441]
float64
5


In [55]:
rand_array = np.random.rand(2,2)
print('rand_array:')
print(rand_array)
print(rand_array.dtype)
print(len(rand_array))

rand_array:
[[0.55181519 0.12246879]
 [0.1921176  0.84078135]]
float64
2


In [56]:
rand_array = np.random.rand(2,3,4)
print('rand_array:')
print(rand_array)
print(rand_array.dtype)
print(len(rand_array))

rand_array:
[[[0.64740744 0.57314879 0.21593162 0.73495142]
  [0.98845832 0.97813051 0.71932663 0.51328523]
  [0.10139647 0.06375141 0.34099671 0.94191313]]

 [[0.01454221 0.07168974 0.25439603 0.14640237]
  [0.30310198 0.07491995 0.48670859 0.62117147]
  [0.34398883 0.9796037  0.43991699 0.99164307]]]
float64
2


In [57]:
# Random generation - changes on each method call
for i in range(3):
    rand_array = np.random.rand(3)
    print(f'rand_array {i}:')
    print(rand_array)

rand_array 0:
[0.15421921 0.83570411 0.29274113]
rand_array 1:
[0.29698995 0.74790716 0.15230653]
rand_array 2:
[0.08703578 0.01859837 0.70457004]


### numpy.random.randint()
#### Generate random numbers from a given range, in a given shape, uniformly distributed and excluding the high value
random.randint(low, high=None, size=None, dtype=int)

In [58]:
rand_array = np.random.randint(10, size=30)
print('rand_array:')
print(rand_array)
print(rand_array.dtype)
print(len(rand_array))

rand_array:
[9 8 5 6 8 1 4 8 2 3 5 8 0 8 1 5 2 4 9 2 9 0 5 2 1 4 5 5 2 5]
int32
30


In [59]:
rand_array = np.random.randint(11, size=30)
print('rand_array:')
print(rand_array)
print(rand_array.dtype)
print(len(rand_array))

rand_array:
[ 9  4  9  0  1  0  8  6  1  0  2  5  2  6  3  9  0  8  1  0  4  5  9  5
  6  8  3 10  8  7]
int32
30


In [60]:
# Binary generator
rand_array = np.random.randint(2, size=10)
print('rand_array:')
print(rand_array)
print(rand_array.dtype)
print(len(rand_array))

rand_array:
[0 1 0 1 1 0 0 0 1 1]
int32
10


In [61]:
rand_array = np.random.randint(10, 20, size=(5,5))
print('rand_array:')
print(rand_array)
print(rand_array.dtype)
print(len(rand_array))

rand_array:
[[15 12 12 15 16]
 [18 16 10 13 12]
 [16 11 14 15 13]
 [17 10 13 10 11]
 [17 10 19 16 12]]
int32
5


### numpy.random.shuffle()
#### Shuffles an array in-place
random.shuffle(x)

In [62]:
a = np.arange(10)
print('a:')
print(a)
np.random.shuffle(a)
print('shuffled:')
print(a)

a:
[0 1 2 3 4 5 6 7 8 9]
shuffled:
[8 2 9 4 0 1 5 6 7 3]


In [63]:
# Shuffeling a multi-dimensional array will only shuffle the first axis
a = np.arange(9).reshape((3, 3))
print('a:')
print(a)
np.random.shuffle(a)
print('shuffled:')
print(a)

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shuffled:
[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Other distribution sampling methods
#### Numpy provides many different sampling methods, such as:
#### Binomial - https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html
#### Laplace - https://numpy.org/doc/stable/reference/random/generated/numpy.random.laplace.html
#### Poisson - https://numpy.org/doc/stable/reference/random/generated/numpy.random.poisson.html
#### Normal - https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html

# 8. Advanced array manipulation
### Below are some built-in methods that enable array manipulation, shape manipulation, concatenation and more.
### Find more at: https://numpy.org/doc/stable/reference/routines.array-manipulation.html
Numpy provides built-in methods that use vectorized calculations (in opposite to loop calculations) that make the code run faster. Below are some selected functions that help manipulate data as we need.

### numpy.squeeze()
#### Returns an array while squeezing dimensions of length 1
numpy.squeeze(a, axis=None)

In [64]:
a = np.array([[1], [2], [3]])
print('a:')
print(a)
print(f'a shape: {a.shape}')
squeeze = np.squeeze(a)
print('squeezed:')
print(squeeze)
print(f'squeezed shape: {squeeze.shape}')

a:
[[1]
 [2]
 [3]]
a shape: (3, 1)
squeezed:
[1 2 3]
squeezed shape: (3,)


In [65]:
a = np.array([[[1], [2], [3]]])
print('a:')
print(a)
print(f'a shape: {a.shape}')
squeeze = np.squeeze(a, axis=0)
print('squeezed axis = 0:') # Squeeze axis 0, possible since its length is 1
print(squeeze)
squeeze = np.squeeze(a, axis=2) # Squeeze axis 2, possible since its length is 1
print('squeezed axis = 2:')
print(squeeze)
print(f'squeezed shape: {squeeze.shape}')
squeeze = np.squeeze(a)
print('squeezed axis = None:') # Squeeze any axis with length = 1
print(squeeze)
print(f'squeezed shape: {squeeze.shape}')

a:
[[[1]
  [2]
  [3]]]
a shape: (1, 3, 1)
squeezed axis = 0:
[[1]
 [2]
 [3]]
squeezed axis = 2:
[[1 2 3]]
squeezed shape: (1, 3)
squeezed axis = None:
[1 2 3]
squeezed shape: (3,)


### numpy.ravel()
#### Returns a contiguous 1D array
numpy.ravel(a, order='C')

In [66]:
a = np.array([[1, 2, 3], [3, 2, 1]])
print('a:')
print(a)
print('ravel:')
print(np.ravel(a))

a:
[[1 2 3]
 [3 2 1]]
ravel:
[1 2 3 3 2 1]


### numpy.flatten()
#### Returns a copy of the array as a 1D collapsed array
ndarray.flatten(order='C')

In [67]:
a = np.array([[1, 2, 3], [3, 2, 1]])
print('a:')
print(a)
print('flatten:')
print(a.flatten())

a:
[[1 2 3]
 [3 2 1]]
flatten:
[1 2 3 3 2 1]


### numpy.swapaxes()
#### Swap two axes of an array
numpy.swapaxes(a, axis1, axis2)

In [68]:
a = np.array([[0, 1, 2], [10, 11, 12], [20, 21, 22]])
print('a:')
print(a)
swapped = np.swapaxes(a,0,1)
print('swapped:')
print(swapped)

a:
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
swapped:
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]]


In [69]:
a = np.array([[[0, 1, 2], [10, 11, 12], [20, 21, 22]]])
print('a:')
print(a)
print(f'a shape {a.shape}')
swapped = np.swapaxes(a,0,1)
print('swapped axes 0 and 1:')
print(swapped)
print(f'swapped shape {swapped.shape}')
swapped = np.swapaxes(a,0,2)
print('swapped axes 0 and 2:')
print(swapped)
print(f'swapped shape {swapped.shape}')
swapped = np.swapaxes(a,1,2)
print('swapped axes 1 and 2:')
print(swapped)
print(f'swapped shape {swapped.shape}')

a:
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]]
a shape (1, 3, 3)
swapped axes 0 and 1:
[[[ 0  1  2]]

 [[10 11 12]]

 [[20 21 22]]]
swapped shape (3, 1, 3)
swapped axes 0 and 2:
[[[ 0]
  [10]
  [20]]

 [[ 1]
  [11]
  [21]]

 [[ 2]
  [12]
  [22]]]
swapped shape (3, 3, 1)
swapped axes 1 and 2:
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]]
swapped shape (1, 3, 3)


### numpy.unique()
#### Get the sorted unique values in an array
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)

In [70]:
a = np.random.randint(10, size=10)
unique_values = np.unique(a)
print('a:')
print(a)
print('unique values in a:')
print(unique_values)

a:
[5 1 8 6 0 0 8 7 4 5]
unique values in a:
[0 1 4 5 6 7 8]


In [71]:
# Get the unique rows (values in axis 0) in a 2d array
a = np.array([[1, 0, 0], [2, 3, 4], [1, 0, 0]])
unique_values = np.unique(a, axis=0)
print('a:')
print(a)
unique_values = np.unique(a) # unique elements
print('unique values in a axis = None:')
print(unique_values)
unique_values = np.unique(a, axis=0) # unique rows
print('unique rows in a axis = 0:')
print(unique_values)

a:
[[1 0 0]
 [2 3 4]
 [1 0 0]]
unique values in a axis = None:
[0 1 2 3 4]
unique rows in a axis = 0:
[[1 0 0]
 [2 3 4]]


### numpy.hstack()
#### Stack array horrizontaly (column wise)
numpy.hstack(tup) where tup = arrays as tuple

In [72]:
a = np.array((0,0,0))
b = np.array((1,1,1))
stacked = np.hstack((a,b))
print('a:')
print(a)
print(f'a shape {a.shape}')
print('b:')
print(b)
print(f'b shape {b.shape}')
print('horizontal stacked:')
print(stacked)
print(f'stacked shape {stacked.shape}')

a:
[0 0 0]
a shape (3,)
b:
[1 1 1]
b shape (3,)
horizontal stacked:
[0 0 0 1 1 1]
stacked shape (6,)


In [73]:
a = np.array((0,0,0))
b = np.array((1,1,1))
c = np.array((2,2,2))
stacked = np.hstack((a,b,c))
print('a:')
print(a)
print(f'a shape {a.shape}')
print('b:')
print(b)
print(f'b shape {b.shape}')
print('c:')
print(c)
print(f'c shape {c.shape}')
print('horizontal stacked:')
print(stacked)
print(f'stacked shape {stacked.shape}')

a:
[0 0 0]
a shape (3,)
b:
[1 1 1]
b shape (3,)
c:
[2 2 2]
c shape (3,)
horizontal stacked:
[0 0 0 1 1 1 2 2 2]
stacked shape (9,)


### numpy.vstack()
#### Stack array vertically (row wise)
numpy.vstack(tup) where tup = arrays as tuple

In [74]:
a = np.array((0,0,0))
b = np.array((1,1,1))
stacked = np.vstack((a,b))
print('a:')
print(a)
print(f'a shape {a.shape}')
print('b:')
print(b)
print(f'b shape {b.shape}')
print('vertical stacked:')
print(stacked)
print(f'stacked shape {stacked.shape}')

a:
[0 0 0]
a shape (3,)
b:
[1 1 1]
b shape (3,)
vertical stacked:
[[0 0 0]
 [1 1 1]]
stacked shape (2, 3)


In [75]:
a = np.array((0,0,0))
b = np.array((1,1,1))
c = np.array((2,2,2))
stacked = np.vstack((a,b,c))
print('a:')
print(a)
print(f'a shape {a.shape}')
print('b:')
print(b)
print(f'b shape {b.shape}')
print('c:')
print(c)
print(f'c shape {c.shape}')
print('vertical stacked:')
print(stacked)
print(f'stacked shape {stacked.shape}')

a:
[0 0 0]
a shape (3,)
b:
[1 1 1]
b shape (3,)
c:
[2 2 2]
c shape (3,)
vertical stacked:
[[0 0 0]
 [1 1 1]
 [2 2 2]]
stacked shape (3, 3)


### Other useful manipulation methods
#### Numpy provides many different manipulation methods, such as:
#### Split - https://numpy.org/doc/stable/reference/generated/numpy.split.html
#### Padding - https://numpy.org/doc/stable/reference/generated/numpy.pad.html
#### Resize - https://numpy.org/doc/stable/reference/generated/numpy.resize.html
#### Stack (along a new axis) - https://numpy.org/doc/stable/reference/generated/numpy.stack.html
#### Concatenate (along an existing axis) -  https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

# 9. Statistics
### Some of the commonly used statistics related methods.
### Find more at: https://numpy.org/doc/stable/reference/routines.array-creation.html
Numpy provides built-in statistics related methods that are very commonly used in ml, data science and computer vision.

### numpy.median()
#### Compute the median along a given axis
numpy.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

In [76]:
a = np.random.randint(10, size=10)
print('a:')
print(a)
median = np.median(a)
print('median:')
print(median)

a:
[0 2 5 9 2 0 9 9 0 4]
median:
3.0


In [77]:
a = np.random.randint(5, size=24).reshape((4,6))
print('a:')
print(a)
median = np.median(a, axis = 0)
print(f'median in axis = 0:')
print(median)
median = np.median(a, axis = 1)
print(f'median in axis = 1:')
print(median)

a:
[[0 0 2 3 4 0]
 [1 2 4 4 3 0]
 [3 0 0 0 0 0]
 [1 0 0 0 2 3]]
median in axis = 0:
[1.  0.  1.  1.5 2.5 0. ]
median in axis = 1:
[1.  2.5 0.  0.5]


### numpy.mean()
#### Compute the mean along a given axis
numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

In [78]:
a = np.random.randint(10, size=10)
print('a:')
print(a)
mean = np.mean(a)
print('mean:')
print(mean)

a:
[5 6 4 6 2 1 5 4 8 2]
mean:
4.3


In [79]:
a = np.random.randint(5, size=24).reshape((4,6))
print('a:')
print(a)
mean = np.mean(a, axis = 0)
print(f'mean in axis = 0:')
print(mean)
mean = np.mean(a, axis = 1)
print(f'mean in axis = 1:')
print(mean)

a:
[[0 1 2 3 3 4]
 [0 3 1 0 1 0]
 [4 1 1 3 4 3]
 [4 2 0 2 0 2]]
mean in axis = 0:
[2.   1.75 1.   2.   2.   2.25]
mean in axis = 1:
[2.16666667 0.83333333 2.66666667 1.66666667]


### numpy.var()
#### Compute the variance along a given axis
numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)

In [80]:
a = np.random.randint(10, size=10)
print('a:')
print(a)
var = np.var(a)
print('var:')
print(var)

a:
[4 4 3 5 1 9 1 8 1 3]
var:
7.090000000000001


In [81]:
a = np.random.randint(5, size=24).reshape((4,6))
print('a:')
print(a)
var = np.var(a, axis = 0)
print(f'var in axis = 0:')
print(var)
var = np.var(a, axis = 1)
print(f'var in axis = 1:')
print(var)

a:
[[0 3 2 3 3 4]
 [4 0 2 4 1 4]
 [0 2 4 2 4 4]
 [3 4 3 2 4 4]]
var in axis = 0:
[3.1875 2.1875 0.6875 0.6875 1.5    0.    ]
var in axis = 1:
[1.58333333 2.58333333 2.22222222 0.55555556]


### numpy.cov()
#### Compute (estimate) a covariance matrix
numpy.cov(m, y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None, *, dtype=None)

In [82]:
a = np.random.randint(5, size=24).reshape((4,6))
print('a:')
print(a)
covariance_mat = np.cov(a)
print(f'covariance matrix for a:')
print(covariance_mat)

a:
[[2 0 1 2 3 1]
 [2 1 3 0 3 4]
 [0 0 2 4 4 2]
 [1 1 4 4 3 0]]
covariance matrix for a:
[[ 1.1         0.1         1.2         0.7       ]
 [ 0.1         2.16666667  0.         -0.83333333]
 [ 1.2         0.          3.2         2.        ]
 [ 0.7        -0.83333333  2.          2.96666667]]


### Other useful statistics methods
#### Numpy provides many different statistics methods, such as:
#### Average (wighted average) - https://numpy.org/doc/stable/reference/generated/numpy.average.html
#### Cross correlation - https://numpy.org/doc/stable/reference/generated/numpy.correlate.html
#### Histogram computing - https://numpy.org/doc/stable/reference/generated/numpy.histogram.html
#### Peak to peak (value range calculation in axis) - https://numpy.org/doc/stable/reference/generated/numpy.ptp.html

# 10. Linear algebra
### Some of the commonly used linear algebrea related methods.
### Find more at: https://numpy.org/doc/stable/reference/routines.linalg.html
Numpy provides built-in linear algebrea related methods that are very commonly used in ml, data science and computer vision.

### numpy.matmul(), @
#### Calculate the matrix product of two arrays
numpy.matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis])

In [83]:
a = np.random.randint(4, size=6).reshape((2,3))
b = np.random.randint(4, size=6).reshape((3,2))
print('a:')
print(a)
print(f'a shape {a.shape}') # shape (n,k)
print('b:')
print(b)
print(f'b shape {b.shape}') # shape (k,m)
mult = np.matmul(a, b)
print('mult = np.matmul(a, b):')
print(mult)
print(f'mult shape {mult.shape}') # shape of (n,k),(k,m)->(n,m)
mult = a@b
print('mult = a@b:')
print(mult)
print(f'mult shape {mult.shape}') # shape of (n,k),(k,m)->(n,m)

a:
[[2 0 1]
 [3 0 3]]
a shape (2, 3)
b:
[[0 0]
 [3 0]
 [2 0]]
b shape (3, 2)
mult = np.matmul(a, b):
[[2 0]
 [6 0]]
mult shape (2, 2)
mult = a@b:
[[2 0]
 [6 0]]
mult shape (2, 2)


In [84]:
a = np.random.randint(4, size=6).reshape((2,3))
b = np.random.randint(4, size=3)
print('a:')
print(a)
print(f'a shape {a.shape}') # shape (n,k)
print('b:')
print(b)
print(f'b shape {b.shape}') # shape (k,m)
mult = np.matmul(a, b)
print('mult = np.matmul(a, b):')
print(mult)
print(f'mult shape {mult.shape}') # shape of (n,k),(k,m)->(n,m)
mult = a@b
print('mult = a@b:')
print(mult)
print(f'mult shape {mult.shape}') # shape of (n,k),(k,m)->(n,m)

a:
[[3 3 1]
 [1 0 3]]
a shape (2, 3)
b:
[0 3 2]
b shape (3,)
mult = np.matmul(a, b):
[11  6]
mult shape (2,)
mult = a@b:
[11  6]
mult shape (2,)


### numpy.dot()
#### Calculate the dot product of two arrays
numpy.dot(a, b, out=None)

In [85]:
a = np.random.randint(4, size=6).reshape((2,3))
b = np.random.randint(4, size=6).reshape((2,3,1))
print('a:')
print(a)
print(f'a shape {a.shape}') # shape (n,k)
print('b:')
print(b)
print(f'b shape {b.shape}') # shape (k,m)
dot = np.dot(a, b)
print('dot = np.dot(a, b):')
print(dot)
print(f'dot shape {dot.shape}') # shape of (n,k),(k,m)->(n,m)

a:
[[1 1 0]
 [1 2 2]]
a shape (2, 3)
b:
[[[2]
  [0]
  [2]]

 [[1]
  [3]
  [1]]]
b shape (2, 3, 1)
dot = np.dot(a, b):
[[[2]
  [4]]

 [[6]
  [9]]]
dot shape (2, 2, 1)


### numpy.linalg.multi_dot()
#### Calculate the dot product of two or more array while automatically selecting the fastest order
linalg.multi_dot(arrays, *, out=None)

In [86]:
# All will have the same results, when using with big data, np.linalg.multi_dot will optimize and be much faster
a = np.random.random((2, 10))
b = np.random.random((10, 3))
c = np.random.random((3, 5))
d = np.random.random((5, 3))
multi_dot = np.linalg.multi_dot([a, b, c, d])
print('using np.linalg.multi_dot()')
print(multi_dot)
multi_dot_chained1 = np.dot(np.dot(np.dot(a, b), c), d)
print('using np.dot(np.dot(np.dot(a, b), c), d)')
print(multi_dot_chained1)
multi_dot_chained1 = a.dot(b).dot(c).dot(d)
print('using a.dot(b).dot(c).dot(d)')
print(multi_dot_chained1)

using np.linalg.multi_dot()
[[ 8.60833202  7.90517962  7.22464214]
 [11.15883726 10.1199047   9.13516918]]
using np.dot(np.dot(np.dot(a, b), c), d)
[[ 8.60833202  7.90517962  7.22464214]
 [11.15883726 10.1199047   9.13516918]]
using a.dot(b).dot(c).dot(d)
[[ 8.60833202  7.90517962  7.22464214]
 [11.15883726 10.1199047   9.13516918]]


### numpy.linalg.det()
#### Calculate the determinant of an array
linalg.det(a)

In [87]:
a = np.array([[4, 2], [1, 3]])
det = np.linalg.det(a)
print('a:')
print(a)
print('determinant of a:')
print(det)

a:
[[4 2]
 [1 3]]
determinant of a:
10.000000000000002


In [88]:
a = np.array([[[4, 2], [1, 3]],[[7, 3], [6, 6]]])
det = np.linalg.det(a)
print('a:')
print(a)
print(f'shape {a.shape}')
print('determinant of a:')
print(det)
print(f'shape {det.shape}')

a:
[[[4 2]
  [1 3]]

 [[7 3]
  [6 6]]]
shape (2, 2, 2)
determinant of a:
[10. 24.]
shape (2,)


### numpy.linalg.inv()
#### Compute the inverse of a matrix (M^-1)
linalg.inv(a)

In [3]:
a = np.array([[[4, 2], [1, 3]],[[7, 3], [6, 6]]])
ainv = np.linalg.inv(a)
print('a:')
print(a)
print(f'shape {a.shape}')
print('a inverse:')
print(ainv)
print(f'shape {ainv.shape}')

a:
[[[4 2]
  [1 3]]

 [[7 3]
  [6 6]]]
shape (2, 2, 2)
a inverse:
[[[ 0.3        -0.2       ]
  [-0.1         0.4       ]]

 [[ 0.25       -0.125     ]
  [-0.25        0.29166667]]]
shape (2, 2, 2)


### numpy.linalg.solve()
#### Solve a system of linear equations (equation matrix), returns the results as an array in order
linalg.solve(a, b)

In [89]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
# Matches the equations:
# x + 2y = 1
# 3x + 5y = 2
# Or the matrix:
# |1 2||x| |1|
# |3 5||y|=|2| 
results = np.linalg.solve(a, b)
print('Solving:')
print('x + 2y = 1')
print('3x + 5y = 2')
print('Result:')
print(f'Results vector {results}')
print(f'Accurate results x={results[0].round()}, y={results[1].round()}')

Solving:
x + 2y = 1
3x + 5y = 2
Result:
Results vector [-1.  1.]
Accurate results x=-1.0, y=1.0


### Other useful linear algebra methods
#### Numpy provides many different linear algebra methods, such as:
#### Vdot (vector dot) - https://numpy.org/doc/stable/reference/generated/numpy.vdot.html
#### Inner product - https://numpy.org/doc/stable/reference/generated/numpy.inner.html
#### Outer product - https://numpy.org/doc/stable/reference/generated/numpy.outer.html