In [1]:
#import numpy -> use numpy. to use the library
import numpy as np# use np. to use the library

# Basic array creation

In [20]:
a = np.array([1,2,3])
b = np.array([1.,2.,3.])
c = np.array([True, True, False])

In [17]:
print('a:')
print(a)
type(a)
a.dtype

a:
[1 2 3]


dtype('int32')

In [18]:
print('b:')
print(b)
type(b)
b.dtype

b:
[1. 2. 3.]


dtype('float64')

In [21]:
print('c:')
print(c)
type(c)
c.dtype

c:
[ True  True False]


dtype('bool')

# Dimensions/shapes

In [27]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[1,2,3]])
c = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

In [39]:
print('a:')
print(a)
print('ndim - number of dimensions:')
print(a.ndim)
print('shape:')
print(a.shape)
print(a.shape[0])

a:
[1 2 3]
ndim - number of dimensions:
1
shape:
(3,)
3


In [40]:
print('b:')
print(b)
print('ndim - number of dimensions:')
print(b.ndim)
print('shape:')
print(b.shape)
print(b.shape[0],b.shape[1])

b:
[[1 2 3]
 [1 2 3]]
ndim - number of dimensions:
2
shape:
(2, 3)
2 3


In [41]:
print('c:')
print(c)
print('ndim - number of dimensions:')
print(c.ndim)
print('shape:')
print(c.shape)
print(c.shape[0],c.shape[1],c.shape[2])

c:
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
ndim - number of dimensions:
3
shape:
(2, 2, 3)
2 2 3


In [35]:
print('Access 1st element in each array:')
print('a:')
print(a[0])
print('b:')
print(b[0,0])
print('c:')
print(c[0,0,0])

Access 1st element in each array:
a:
1
b:
1
c:
1


In [ ]:
print('Access i\'th element in each array:')
print('a:')
print(a[0])
print('b:')
print(b[0,0])
print('c:')
print(c[0,0,0])